name: 'github-action-jest'
description: 'A github action for running jest. With code coverage!'
author: 'jlndk'
# inputs:
#   milliseconds: # change this
#     required: true
#     description: 'input description here'
#     default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
