name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Yarn Cache Directory Path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-deps-

      - name: Install Dependencies
        run: yarn --pure-lockfile --production=false

      - name: Build
        run: yarn run build

      - name: Bundle package
        run: yarn run package

      - name: Run linting
        run: yarn run lint

      - uses: ./
        with:
          test-command: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  failing-tests:
    name: 'Failing tests (on purpose)'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --pure-lockfile --production=false

      - name: Build
        run: yarn run build

      - name: Package
        run: yarn run package

      - uses: ./
        with:
          test-command: yarn test:demo
          # Dont post code coverage for the demo tests
          coverage-comment: false
          # Dont mark action as failed if jest returns non-zero exit code
          fail-action-if-jest-fails: false
